LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric.ALL;

ENTITY CBS IS
    PORT (
        A : IN STD_LOGIC_VECTOR(63 DOWNTO 0);
        S1 : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
        S2 : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
        Result : OUT STD_LOGIC_VECTOR(63 DOWNTO 0)
    );
END ENTITY CBS;

ARCHITECTURE Struct OF CBS IS
BEGIN
END Struct;